# Generated by Django 3.0.8 on 2020-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, upload_to='tutorial/original/'),
        ),
    ]
